#!/bin/bash
set -euo pipefail

export GOTOOLCHAIN=local

PROJECT_DIR="/root/koris-next"
INSTALL_DIR="/opt/koris-next/panel"

cd "$PROJECT_DIR"

# Remove build output directories before pull (they get regenerated by npm run build)
# This handles UNTRACKED files (Vite hashed filenames change between builds)
# that would otherwise block git pull with "untracked working tree files would be overwritten"
rm -rf panel/web/admin/www panel/web/portal/www 2>/dev/null || true
git checkout -- panel/web/admin/www panel/web/portal/www 2>/dev/null || true

# Pull latest code
echo "[deploy] Pulling latest code..."
git pull origin main || { echo "[deploy] Pull failed"; exit 1; }

VERSION="$(cat "$PROJECT_DIR/VERSION" 2>/dev/null || echo next-dev)"

# Safety check: abort if there are uncommitted local changes outside build dirs
if ! git diff --quiet -- . ':!panel/web/admin' ':!panel/web/portal' || ! git diff --cached --quiet -- . ':!panel/web/admin' ':!panel/web/portal'; then
  echo "[deploy] ERROR: uncommitted changes found outside build directories"
  echo "[deploy] Commit or stash them before deploying."
  git status --short
  exit 1
fi

echo "[deploy] Version: $VERSION"

if command -v npm >/dev/null 2>&1; then
  echo "[deploy] Installing shared dependencies..."
  (cd panel/web/shared && npm install --no-audit --no-fund)

  echo "[deploy] Building admin frontend..."
  (cd panel/web/admin && npm install --no-audit --no-fund && npm run build)

  echo "[deploy] Building portal frontend..."
  (cd panel/web/portal && npm install --no-audit --no-fund && npm run build)
else
  echo "[deploy] npm not found; assuming prebuilt www/ directories exist"
fi

echo "[deploy] Building panel binary..."
go mod tidy
go build -o /usr/local/bin/panel ./panel/cmd/panel
chmod +x /usr/local/bin/panel

copy_dir() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  rm -rf "$dst"
  if [ -d "$src" ]; then
    cp -a "$src" "$dst"
  else
    mkdir -p "$dst"
  fi
}

echo "[deploy] Copying static files..."
copy_dir "$PROJECT_DIR/panel/migrations" "$INSTALL_DIR/migrations"
copy_dir "$PROJECT_DIR/panel/web/admin/www" "$INSTALL_DIR/web/admin/www"
copy_dir "$PROJECT_DIR/panel/web/portal/www" "$INSTALL_DIR/web/portal/www"

echo "[deploy] Restarting panel service..."
# Update version in panel.env so the running binary picks it up
if [ -f /etc/panel/panel.env ]; then
  if grep -q '^PANEL_VERSION=' /etc/panel/panel.env; then
    sed -i "s|^PANEL_VERSION=.*|PANEL_VERSION='${VERSION}'|" /etc/panel/panel.env
  else
    echo "PANEL_VERSION='${VERSION}'" >> /etc/panel/panel.env
  fi
  echo "[deploy] Updated PANEL_VERSION to ${VERSION} in panel.env"
fi
sudo systemctl daemon-reload
sudo systemctl restart panel.service

sleep 2

PANEL_ADDR="$(grep -E '^PANEL_ADDR=' /etc/panel/panel.env 2>/dev/null | cut -d= -f2 | tr -d "'"\" || true)"
PANEL_ADDR="${PANEL_ADDR:-127.0.0.1:8088}"

echo "[deploy] Running health check on http://${PANEL_ADDR}/api/health ..."
if curl -fsS "http://${PANEL_ADDR}/api/health" >/dev/null 2>&1; then
  echo "[deploy] Health check passed."
else
  echo "[deploy] Health check failed. Showing recent logs:"
  journalctl -u panel -n 50 --no-pager
  exit 1
fi

echo "[deploy] Done."

# === Post-deploy diagnostics (auto-output for debugging) ===
echo ""
echo "=== [deploy] Post-Deploy Log Output ==="
echo "[deploy] Last 20 panel logs:"
journalctl -u panel -n 20 --no-pager -o short-iso 2>/dev/null || echo "  (journalctl not available)"

echo ""
echo "[deploy] Service status:"
systemctl is-active panel 2>/dev/null || echo "  panel service status unknown"

# Quick health check with timeout
echo ""
echo "[deploy] Health check response:"
curl -s --max-time 5 http://127.0.0.1:${PANEL_PORT:-8088}/api/health 2>/dev/null || echo "  (health check failed or timed out)"

echo ""
echo "[deploy] Diagnostics endpoint:"
curl -s --max-time 10 http://127.0.0.1:${PANEL_PORT:-8088}/api/diagnostics/status 2>/dev/null || echo "  (diagnostics not available - may need auth)"

echo ""
echo "=== [deploy] End of diagnostics ==="
