-- Migration 052: Node Groups and Load Balancing
-- Requirements: 9.1, 9.2, 9.5, 10.2, 12.1, 12.4

CREATE TABLE IF NOT EXISTS node_groups (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL DEFAULT '',
    description TEXT,
    load_balancing_enabled TINYINT(1) NOT NULL DEFAULT 0,
    max_load_percent INT NOT NULL DEFAULT 85,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_node_groups_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE nodes ADD COLUMN group_id BIGINT DEFAULT NULL;
ALTER TABLE nodes ADD COLUMN max_capacity INT NOT NULL DEFAULT 100;
ALTER TABLE nodes ADD COLUMN bandwidth_quota_gb INT DEFAULT NULL;
ALTER TABLE nodes ADD COLUMN bandwidth_used_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN bandwidth_reset_at DATETIME DEFAULT NULL;
ALTER TABLE nodes ADD COLUMN agent_version VARCHAR(20) DEFAULT NULL;
ALTER TABLE nodes ADD CONSTRAINT fk_nodes_group FOREIGN KEY (group_id) REFERENCES node_groups(id) ON DELETE SET NULL;
