// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: knode/v1/knode.proto

package knodepb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoreState represents the current state of a VPN core.
type CoreState int32

const (
	CoreState_CORE_STATE_UNSPECIFIED CoreState = 0
	CoreState_CORE_STATE_RUNNING     CoreState = 1
	CoreState_CORE_STATE_STOPPED     CoreState = 2
	CoreState_CORE_STATE_CRASHED     CoreState = 3
)

func (CoreState) Descriptor() protoreflect.EnumDescriptor { return nil }
func (x CoreState) Number() protoreflect.EnumNumber       { return protoreflect.EnumNumber(x) }
func (x CoreState) String() string {
	switch x {
	case CoreState_CORE_STATE_UNSPECIFIED:
		return "CORE_STATE_UNSPECIFIED"
	case CoreState_CORE_STATE_RUNNING:
		return "CORE_STATE_RUNNING"
	case CoreState_CORE_STATE_STOPPED:
		return "CORE_STATE_STOPPED"
	case CoreState_CORE_STATE_CRASHED:
		return "CORE_STATE_CRASHED"
	default:
		return "CORE_STATE_UNSPECIFIED"
	}
}

// HealthStatus represents the overall system health.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor { return nil }
func (x HealthStatus) Number() protoreflect.EnumNumber       { return protoreflect.EnumNumber(x) }
func (x HealthStatus) String() string {
	switch x {
	case HealthStatus_HEALTH_STATUS_UNSPECIFIED:
		return "HEALTH_STATUS_UNSPECIFIED"
	case HealthStatus_HEALTH_STATUS_HEALTHY:
		return "HEALTH_STATUS_HEALTHY"
	case HealthStatus_HEALTH_STATUS_DEGRADED:
		return "HEALTH_STATUS_DEGRADED"
	case HealthStatus_HEALTH_STATUS_UNHEALTHY:
		return "HEALTH_STATUS_UNHEALTHY"
	default:
		return "HEALTH_STATUS_UNSPECIFIED"
	}
}

// TunnelProtocol represents the protocol used for outbound tunnels.
type TunnelProtocol int32

const (
	TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED   TunnelProtocol = 0
	TunnelProtocol_TUNNEL_PROTOCOL_WIREGUARD     TunnelProtocol = 1
	TunnelProtocol_TUNNEL_PROTOCOL_SSH           TunnelProtocol = 2
	TunnelProtocol_TUNNEL_PROTOCOL_VLESS_REALITY TunnelProtocol = 3
	TunnelProtocol_TUNNEL_PROTOCOL_RATHOLE       TunnelProtocol = 4
	TunnelProtocol_TUNNEL_PROTOCOL_GRE           TunnelProtocol = 5
	TunnelProtocol_TUNNEL_PROTOCOL_IPIP          TunnelProtocol = 6
)

func (TunnelProtocol) Descriptor() protoreflect.EnumDescriptor { return nil }
func (x TunnelProtocol) Number() protoreflect.EnumNumber       { return protoreflect.EnumNumber(x) }
func (x TunnelProtocol) String() string {
	switch x {
	case TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED:
		return "TUNNEL_PROTOCOL_UNSPECIFIED"
	case TunnelProtocol_TUNNEL_PROTOCOL_WIREGUARD:
		return "TUNNEL_PROTOCOL_WIREGUARD"
	case TunnelProtocol_TUNNEL_PROTOCOL_SSH:
		return "TUNNEL_PROTOCOL_SSH"
	case TunnelProtocol_TUNNEL_PROTOCOL_VLESS_REALITY:
		return "TUNNEL_PROTOCOL_VLESS_REALITY"
	case TunnelProtocol_TUNNEL_PROTOCOL_RATHOLE:
		return "TUNNEL_PROTOCOL_RATHOLE"
	case TunnelProtocol_TUNNEL_PROTOCOL_GRE:
		return "TUNNEL_PROTOCOL_GRE"
	case TunnelProtocol_TUNNEL_PROTOCOL_IPIP:
		return "TUNNEL_PROTOCOL_IPIP"
	default:
		return "TUNNEL_PROTOCOL_UNSPECIFIED"
	}
}

// TunnelState represents the current state of an outbound tunnel.
type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNSPECIFIED  TunnelState = 0
	TunnelState_TUNNEL_STATE_ACTIVE       TunnelState = 1
	TunnelState_TUNNEL_STATE_CONNECTING   TunnelState = 2
	TunnelState_TUNNEL_STATE_DISCONNECTED TunnelState = 3
	TunnelState_TUNNEL_STATE_ERROR        TunnelState = 4
)

func (TunnelState) Descriptor() protoreflect.EnumDescriptor { return nil }
func (x TunnelState) Number() protoreflect.EnumNumber       { return protoreflect.EnumNumber(x) }
func (x TunnelState) String() string {
	switch x {
	case TunnelState_TUNNEL_STATE_UNSPECIFIED:
		return "TUNNEL_STATE_UNSPECIFIED"
	case TunnelState_TUNNEL_STATE_ACTIVE:
		return "TUNNEL_STATE_ACTIVE"
	case TunnelState_TUNNEL_STATE_CONNECTING:
		return "TUNNEL_STATE_CONNECTING"
	case TunnelState_TUNNEL_STATE_DISCONNECTED:
		return "TUNNEL_STATE_DISCONNECTED"
	case TunnelState_TUNNEL_STATE_ERROR:
		return "TUNNEL_STATE_ERROR"
	default:
		return "TUNNEL_STATE_UNSPECIFIED"
	}
}

// Suppress unused import warnings.
var (
	_ = reflect.TypeOf
	_ = sync.Mutex{}
	_ = timestamppb.Timestamp{}
)

// ============================================================
// Authentication
// ============================================================

type AuthRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Core     string `protobuf:"bytes,3,opt,name=core,proto3" json:"core,omitempty"`
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}
func (x *AuthRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *AuthRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AuthRequest) Reset()                             { *x = AuthRequest{} }
func (x *AuthRequest) String() string                     { return x.Username }

type AuthResponse struct {
	Allowed bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AuthResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}
func (x *AuthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}
func (x *AuthResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *AuthResponse) Reset()                             { *x = AuthResponse{} }
func (x *AuthResponse) String() string                     { return x.Reason }

// ============================================================
// Sessions
// ============================================================

type ConnectRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Core       string `protobuf:"bytes,2,opt,name=core,proto3" json:"core,omitempty"`
	ClientIp   string `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	AssignedIp string `protobuf:"bytes,4,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
}

func (x *ConnectRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *ConnectRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *ConnectRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}
func (x *ConnectRequest) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}
func (x *ConnectRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ConnectRequest) Reset()                             { *x = ConnectRequest{} }
func (x *ConnectRequest) String() string                     { return x.Username }

type ConnectResponse struct {
	SessionId  string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AssignedIp string `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}
func (x *ConnectResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}
func (x *ConnectResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ConnectResponse) Reset()                             { *x = ConnectResponse{} }
func (x *ConnectResponse) String() string                     { return x.SessionId }

type DisconnectRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Core     string `protobuf:"bytes,2,opt,name=core,proto3" json:"core,omitempty"`
}

func (x *DisconnectRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *DisconnectRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *DisconnectRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DisconnectRequest) Reset()                             { *x = DisconnectRequest{} }
func (x *DisconnectRequest) String() string                     { return x.Username }

type DisconnectResponse struct {
	DisconnectedCount int32 `protobuf:"varint,1,opt,name=disconnected_count,json=disconnectedCount,proto3" json:"disconnected_count,omitempty"`
}

func (x *DisconnectResponse) GetDisconnectedCount() int32 {
	if x != nil {
		return x.DisconnectedCount
	}
	return 0
}
func (x *DisconnectResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *DisconnectResponse) Reset()                             { *x = DisconnectResponse{} }
func (x *DisconnectResponse) String() string                     { return "" }

type ListSessionsRequest struct {
	Core string `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
}

func (x *ListSessionsRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ListSessionsRequest) Reset()                             { *x = ListSessionsRequest{} }
func (x *ListSessionsRequest) String() string                     { return x.Core }

type ListSessionsResponse struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}
func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ListSessionsResponse) Reset()                             { *x = ListSessionsResponse{} }
func (x *ListSessionsResponse) String() string                     { return "" }

type Session struct {
	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Username    string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Core        string                 `protobuf:"bytes,3,opt,name=core,proto3" json:"core,omitempty"`
	ClientIp    string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	AssignedIp  string                 `protobuf:"bytes,5,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	ConnectedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	RxBytes     int64                  `protobuf:"varint,7,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes     int64                  `protobuf:"varint,8,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}
func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *Session) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *Session) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}
func (x *Session) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}
func (x *Session) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}
func (x *Session) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}
func (x *Session) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}
func (x *Session) ProtoReflect() protoreflect.Message { return nil }
func (x *Session) Reset()                             { *x = Session{} }
func (x *Session) String() string                     { return x.SessionId }

// ============================================================
// Cores
// ============================================================

type EnableCoreRequest struct {
	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ListenPort  int32  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ExtraConfig []byte `protobuf:"bytes,3,opt,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty"`
}

func (x *EnableCoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *EnableCoreRequest) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}
func (x *EnableCoreRequest) GetExtraConfig() []byte {
	if x != nil {
		return x.ExtraConfig
	}
	return nil
}
func (x *EnableCoreRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *EnableCoreRequest) Reset()                             { *x = EnableCoreRequest{} }
func (x *EnableCoreRequest) String() string                     { return x.Type }

type EnableCoreResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EnableCoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *EnableCoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *EnableCoreResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *EnableCoreResponse) Reset()                             { *x = EnableCoreResponse{} }
func (x *EnableCoreResponse) String() string                     { return x.Message }

type DisableCoreRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DisableCoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *DisableCoreRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DisableCoreRequest) Reset()                             { *x = DisableCoreRequest{} }
func (x *DisableCoreRequest) String() string                     { return x.Type }

type DisableCoreResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DisableCoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *DisableCoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *DisableCoreResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *DisableCoreResponse) Reset()                             { *x = DisableCoreResponse{} }
func (x *DisableCoreResponse) String() string                     { return x.Message }

type CoreStatusRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CoreStatusRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *CoreStatusRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CoreStatusRequest) Reset()                             { *x = CoreStatusRequest{} }
func (x *CoreStatusRequest) String() string                     { return x.Type }

type CoreStatusResponse struct {
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	State          CoreState              `protobuf:"varint,2,opt,name=state,proto3,enum=knode.v1.CoreState" json:"state,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	Pid            int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	LastError      string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastStarted    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_started,json=lastStarted,proto3" json:"last_started,omitempty"`
}

func (x *CoreStatusResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *CoreStatusResponse) GetState() CoreState {
	if x != nil {
		return x.State
	}
	return CoreState_CORE_STATE_UNSPECIFIED
}
func (x *CoreStatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}
func (x *CoreStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}
func (x *CoreStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}
func (x *CoreStatusResponse) GetLastStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStarted
	}
	return nil
}
func (x *CoreStatusResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CoreStatusResponse) Reset()                             { *x = CoreStatusResponse{} }
func (x *CoreStatusResponse) String() string                     { return x.Type }

type AllCoreStatusesRequest struct{}

func (x *AllCoreStatusesRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AllCoreStatusesRequest) Reset()                             { *x = AllCoreStatusesRequest{} }
func (x *AllCoreStatusesRequest) String() string                     { return "" }

type AllCoreStatusesResponse struct {
	Cores []*CoreStatusResponse `protobuf:"bytes,1,rep,name=cores,proto3" json:"cores,omitempty"`
}

func (x *AllCoreStatusesResponse) GetCores() []*CoreStatusResponse {
	if x != nil {
		return x.Cores
	}
	return nil
}
func (x *AllCoreStatusesResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *AllCoreStatusesResponse) Reset()                             { *x = AllCoreStatusesResponse{} }
func (x *AllCoreStatusesResponse) String() string                     { return "" }

// ============================================================
// Users
// ============================================================

type SyncUsersRequest struct {
	Core  string       `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
	Users []*UserEntry `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SyncUsersRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *SyncUsersRequest) GetUsers() []*UserEntry {
	if x != nil {
		return x.Users
	}
	return nil
}
func (x *SyncUsersRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *SyncUsersRequest) Reset()                             { *x = SyncUsersRequest{} }
func (x *SyncUsersRequest) String() string                     { return x.Core }

type UserEntry struct {
	Username string      `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string      `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Limits   *UserLimits `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	Enabled  bool        `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *UserEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *UserEntry) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}
func (x *UserEntry) GetLimits() *UserLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}
func (x *UserEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}
func (x *UserEntry) ProtoReflect() protoreflect.Message { return nil }
func (x *UserEntry) Reset()                             { *x = UserEntry{} }
func (x *UserEntry) String() string                     { return x.Username }

type UserLimits struct {
	MaxDataBytes      int64 `protobuf:"varint,1,opt,name=max_data_bytes,json=maxDataBytes,proto3" json:"max_data_bytes,omitempty"`
	MaxConnections    int32 `protobuf:"varint,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	BandwidthLimitBps int64 `protobuf:"varint,3,opt,name=bandwidth_limit_bps,json=bandwidthLimitBps,proto3" json:"bandwidth_limit_bps,omitempty"`
}

func (x *UserLimits) GetMaxDataBytes() int64 {
	if x != nil {
		return x.MaxDataBytes
	}
	return 0
}
func (x *UserLimits) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}
func (x *UserLimits) GetBandwidthLimitBps() int64 {
	if x != nil {
		return x.BandwidthLimitBps
	}
	return 0
}
func (x *UserLimits) ProtoReflect() protoreflect.Message { return nil }
func (x *UserLimits) Reset()                             { *x = UserLimits{} }
func (x *UserLimits) String() string                     { return "" }

type SyncUsersResponse struct {
	Added   int32 `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Updated int32 `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed int32 `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *SyncUsersResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}
func (x *SyncUsersResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}
func (x *SyncUsersResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}
func (x *SyncUsersResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *SyncUsersResponse) Reset()                             { *x = SyncUsersResponse{} }
func (x *SyncUsersResponse) String() string                     { return "" }

type SetUserLimitsRequest struct {
	Username string      `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Limits   *UserLimits `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *SetUserLimitsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *SetUserLimitsRequest) GetLimits() *UserLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}
func (x *SetUserLimitsRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *SetUserLimitsRequest) Reset()                             { *x = SetUserLimitsRequest{} }
func (x *SetUserLimitsRequest) String() string                     { return x.Username }

type SetUserLimitsResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetUserLimitsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *SetUserLimitsResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *SetUserLimitsResponse) Reset()                             { *x = SetUserLimitsResponse{} }
func (x *SetUserLimitsResponse) String() string                     { return "" }

// ============================================================
// Traffic
// ============================================================

type GetTrafficRequest struct{}

func (x *GetTrafficRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetTrafficRequest) Reset()                             { *x = GetTrafficRequest{} }
func (x *GetTrafficRequest) String() string                     { return "" }

type TrafficReport struct {
	Timestamp *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalRx   int64                   `protobuf:"varint,2,opt,name=total_rx,json=totalRx,proto3" json:"total_rx,omitempty"`
	TotalTx   int64                   `protobuf:"varint,3,opt,name=total_tx,json=totalTx,proto3" json:"total_tx,omitempty"`
	PerUser   map[string]*UserTraffic `protobuf:"bytes,4,rep,name=per_user,json=perUser,proto3" json:"per_user,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TrafficReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}
func (x *TrafficReport) GetTotalRx() int64 {
	if x != nil {
		return x.TotalRx
	}
	return 0
}
func (x *TrafficReport) GetTotalTx() int64 {
	if x != nil {
		return x.TotalTx
	}
	return 0
}
func (x *TrafficReport) GetPerUser() map[string]*UserTraffic {
	if x != nil {
		return x.PerUser
	}
	return nil
}
func (x *TrafficReport) ProtoReflect() protoreflect.Message { return nil }
func (x *TrafficReport) Reset()                             { *x = TrafficReport{} }
func (x *TrafficReport) String() string                     { return "" }

type UserTraffic struct {
	RxBytes int64 `protobuf:"varint,1,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes int64 `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
}

func (x *UserTraffic) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}
func (x *UserTraffic) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}
func (x *UserTraffic) ProtoReflect() protoreflect.Message { return nil }
func (x *UserTraffic) Reset()                             { *x = UserTraffic{} }
func (x *UserTraffic) String() string                     { return "" }

type GetUserTrafficRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetUserTrafficRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *GetUserTrafficRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetUserTrafficRequest) Reset()                             { *x = GetUserTrafficRequest{} }
func (x *GetUserTrafficRequest) String() string                     { return x.Username }

type UserTrafficResponse struct {
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RxBytes  int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes  int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	Since    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
}

func (x *UserTrafficResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *UserTrafficResponse) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}
func (x *UserTrafficResponse) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}
func (x *UserTrafficResponse) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}
func (x *UserTrafficResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *UserTrafficResponse) Reset()                             { *x = UserTrafficResponse{} }
func (x *UserTrafficResponse) String() string                     { return x.Username }

type ResetTrafficRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ResetTrafficRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *ResetTrafficRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ResetTrafficRequest) Reset()                             { *x = ResetTrafficRequest{} }
func (x *ResetTrafficRequest) String() string                     { return x.Username }

type ResetTrafficResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResetTrafficResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *ResetTrafficResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ResetTrafficResponse) Reset()                             { *x = ResetTrafficResponse{} }
func (x *ResetTrafficResponse) String() string                     { return "" }

// ============================================================
// System
// ============================================================

type HealthRequest struct{}

func (x *HealthRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *HealthRequest) Reset()                             { *x = HealthRequest{} }
func (x *HealthRequest) String() string                     { return "" }

type HealthResponse struct {
	Status        HealthStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=knode.v1.HealthStatus" json:"status,omitempty"`
	UptimeSeconds int64             `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Cores         []*CoreHealthInfo `protobuf:"bytes,3,rep,name=cores,proto3" json:"cores,omitempty"`
	System        *SystemMetrics    `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	GoRuntime     *GoRuntimeMetrics `protobuf:"bytes,5,opt,name=go_runtime,json=goRuntime,proto3" json:"go_runtime,omitempty"`
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}
func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}
func (x *HealthResponse) GetCores() []*CoreHealthInfo {
	if x != nil {
		return x.Cores
	}
	return nil
}
func (x *HealthResponse) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}
func (x *HealthResponse) GetGoRuntime() *GoRuntimeMetrics {
	if x != nil {
		return x.GoRuntime
	}
	return nil
}
func (x *HealthResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *HealthResponse) Reset()                             { *x = HealthResponse{} }
func (x *HealthResponse) String() string                     { return "" }

type CoreHealthInfo struct {
	Type             string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	State            CoreState `protobuf:"varint,2,opt,name=state,proto3,enum=knode.v1.CoreState" json:"state,omitempty"`
	Pid              int32     `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	RestartsLastHour int32     `protobuf:"varint,4,opt,name=restarts_last_hour,json=restartsLastHour,proto3" json:"restarts_last_hour,omitempty"`
}

func (x *CoreHealthInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *CoreHealthInfo) GetState() CoreState {
	if x != nil {
		return x.State
	}
	return CoreState_CORE_STATE_UNSPECIFIED
}
func (x *CoreHealthInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}
func (x *CoreHealthInfo) GetRestartsLastHour() int32 {
	if x != nil {
		return x.RestartsLastHour
	}
	return 0
}
func (x *CoreHealthInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *CoreHealthInfo) Reset()                             { *x = CoreHealthInfo{} }
func (x *CoreHealthInfo) String() string                     { return x.Type }

type SystemMetrics struct {
	CpuPercent  float64 `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent  float64 `protobuf:"fixed64,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	DiskPercent float64 `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	RxBps       int64   `protobuf:"varint,4,opt,name=rx_bps,json=rxBps,proto3" json:"rx_bps,omitempty"`
	TxBps       int64   `protobuf:"varint,5,opt,name=tx_bps,json=txBps,proto3" json:"tx_bps,omitempty"`
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}
func (x *SystemMetrics) GetRamPercent() float64 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}
func (x *SystemMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}
func (x *SystemMetrics) GetRxBps() int64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}
func (x *SystemMetrics) GetTxBps() int64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}
func (x *SystemMetrics) ProtoReflect() protoreflect.Message { return nil }
func (x *SystemMetrics) Reset()                             { *x = SystemMetrics{} }
func (x *SystemMetrics) String() string                     { return "" }

type GoRuntimeMetrics struct {
	Goroutines     int32 `protobuf:"varint,1,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	HeapAllocBytes int64 `protobuf:"varint,2,opt,name=heap_alloc_bytes,json=heapAllocBytes,proto3" json:"heap_alloc_bytes,omitempty"`
	GcPauseNs      int64 `protobuf:"varint,3,opt,name=gc_pause_ns,json=gcPauseNs,proto3" json:"gc_pause_ns,omitempty"`
}

func (x *GoRuntimeMetrics) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}
func (x *GoRuntimeMetrics) GetHeapAllocBytes() int64 {
	if x != nil {
		return x.HeapAllocBytes
	}
	return 0
}
func (x *GoRuntimeMetrics) GetGcPauseNs() int64 {
	if x != nil {
		return x.GcPauseNs
	}
	return 0
}
func (x *GoRuntimeMetrics) ProtoReflect() protoreflect.Message { return nil }
func (x *GoRuntimeMetrics) Reset()                             { *x = GoRuntimeMetrics{} }
func (x *GoRuntimeMetrics) String() string                     { return "" }

type RestartRequest struct {
	Core string `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
}

func (x *RestartRequest) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}
func (x *RestartRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *RestartRequest) Reset()                             { *x = RestartRequest{} }
func (x *RestartRequest) String() string                     { return x.Core }

type RestartResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RestartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *RestartResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *RestartResponse) Reset()                             { *x = RestartResponse{} }
func (x *RestartResponse) String() string                     { return x.Message }

// ============================================================
// Firewall
// ============================================================

type OpenPortRequest struct {
	Port     int32  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Comment  string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *OpenPortRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}
func (x *OpenPortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}
func (x *OpenPortRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}
func (x *OpenPortRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *OpenPortRequest) Reset()                             { *x = OpenPortRequest{} }
func (x *OpenPortRequest) String() string                     { return x.Protocol }

type OpenPortResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RuleId  string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
}

func (x *OpenPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *OpenPortResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}
func (x *OpenPortResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *OpenPortResponse) Reset()                             { *x = OpenPortResponse{} }
func (x *OpenPortResponse) String() string                     { return x.RuleId }

type ClosePortRequest struct {
	Port     int32  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *ClosePortRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}
func (x *ClosePortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}
func (x *ClosePortRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ClosePortRequest) Reset()                             { *x = ClosePortRequest{} }
func (x *ClosePortRequest) String() string                     { return x.Protocol }

type ClosePortResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ClosePortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *ClosePortResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ClosePortResponse) Reset()                             { *x = ClosePortResponse{} }
func (x *ClosePortResponse) String() string                     { return "" }

type ListRulesRequest struct{}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ListRulesRequest) Reset()                             { *x = ListRulesRequest{} }
func (x *ListRulesRequest) String() string                     { return "" }

type ListRulesResponse struct {
	Rules []*FirewallRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *ListRulesResponse) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}
func (x *ListRulesResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ListRulesResponse) Reset()                             { *x = ListRulesResponse{} }
func (x *ListRulesResponse) String() string                     { return "" }

type FirewallRule struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol  string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Action    string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Comment   string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Source    string `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *FirewallRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *FirewallRule) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}
func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}
func (x *FirewallRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}
func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}
func (x *FirewallRule) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}
func (x *FirewallRule) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}
func (x *FirewallRule) ProtoReflect() protoreflect.Message { return nil }
func (x *FirewallRule) Reset()                             { *x = FirewallRule{} }
func (x *FirewallRule) String() string                     { return x.Id }

// ============================================================
// Certificates
// ============================================================

type SetCertsRequest struct {
	CoreType string `protobuf:"bytes,1,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Ca       []byte `protobuf:"bytes,2,opt,name=ca,proto3" json:"ca,omitempty"`
	Cert     []byte `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	Key      []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SetCertsRequest) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}
func (x *SetCertsRequest) GetCa() []byte {
	if x != nil {
		return x.Ca
	}
	return nil
}
func (x *SetCertsRequest) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}
func (x *SetCertsRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}
func (x *SetCertsRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *SetCertsRequest) Reset()                             { *x = SetCertsRequest{} }
func (x *SetCertsRequest) String() string                     { return x.CoreType }

type SetCertsResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetCertsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *SetCertsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *SetCertsResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *SetCertsResponse) Reset()                             { *x = SetCertsResponse{} }
func (x *SetCertsResponse) String() string                     { return x.Message }

type GetCertInfoRequest struct {
	CoreType string `protobuf:"bytes,1,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
}

func (x *GetCertInfoRequest) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}
func (x *GetCertInfoRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetCertInfoRequest) Reset()                             { *x = GetCertInfoRequest{} }
func (x *GetCertInfoRequest) String() string                     { return x.CoreType }

type CertInfoResponse struct {
	Subject      string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer       string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	NotBefore    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	SerialNumber string                 `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	IsCa         bool                   `protobuf:"varint,6,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
}

func (x *CertInfoResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}
func (x *CertInfoResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}
func (x *CertInfoResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}
func (x *CertInfoResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}
func (x *CertInfoResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}
func (x *CertInfoResponse) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}
func (x *CertInfoResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CertInfoResponse) Reset()                             { *x = CertInfoResponse{} }
func (x *CertInfoResponse) String() string                     { return x.Subject }

// ============================================================
// Outbound Tunnels
// ============================================================

type SetupTunnelRequest struct {
	Protocol TunnelProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=knode.v1.TunnelProtocol" json:"protocol,omitempty"`
	ExitAddr string         `protobuf:"bytes,2,opt,name=exit_addr,json=exitAddr,proto3" json:"exit_addr,omitempty"`
	ExitPort int32          `protobuf:"varint,3,opt,name=exit_port,json=exitPort,proto3" json:"exit_port,omitempty"`
	Config   []byte         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *SetupTunnelRequest) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}
func (x *SetupTunnelRequest) GetExitAddr() string {
	if x != nil {
		return x.ExitAddr
	}
	return ""
}
func (x *SetupTunnelRequest) GetExitPort() int32 {
	if x != nil {
		return x.ExitPort
	}
	return 0
}
func (x *SetupTunnelRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}
func (x *SetupTunnelRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *SetupTunnelRequest) Reset()                             { *x = SetupTunnelRequest{} }
func (x *SetupTunnelRequest) String() string                     { return x.ExitAddr }

type SetupTunnelResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TunnelId string `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetupTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *SetupTunnelResponse) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}
func (x *SetupTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *SetupTunnelResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *SetupTunnelResponse) Reset()                             { *x = SetupTunnelResponse{} }
func (x *SetupTunnelResponse) String() string                     { return x.TunnelId }

type TeardownTunnelRequest struct {
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
}

func (x *TeardownTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}
func (x *TeardownTunnelRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *TeardownTunnelRequest) Reset()                             { *x = TeardownTunnelRequest{} }
func (x *TeardownTunnelRequest) String() string                     { return x.TunnelId }

type TeardownTunnelResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TeardownTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *TeardownTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *TeardownTunnelResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *TeardownTunnelResponse) Reset()                             { *x = TeardownTunnelResponse{} }
func (x *TeardownTunnelResponse) String() string                     { return x.Message }

type TunnelStatusRequest struct {
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
}

func (x *TunnelStatusRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}
func (x *TunnelStatusRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *TunnelStatusRequest) Reset()                             { *x = TunnelStatusRequest{} }
func (x *TunnelStatusRequest) String() string                     { return x.TunnelId }

type TunnelStatusResponse struct {
	Tunnels []*TunnelInfo `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
}

func (x *TunnelStatusResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}
func (x *TunnelStatusResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *TunnelStatusResponse) Reset()                             { *x = TunnelStatusResponse{} }
func (x *TunnelStatusResponse) String() string                     { return "" }

type TunnelInfo struct {
	TunnelId  string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Protocol  TunnelProtocol         `protobuf:"varint,2,opt,name=protocol,proto3,enum=knode.v1.TunnelProtocol" json:"protocol,omitempty"`
	ExitAddr  string                 `protobuf:"bytes,3,opt,name=exit_addr,json=exitAddr,proto3" json:"exit_addr,omitempty"`
	ExitPort  int32                  `protobuf:"varint,4,opt,name=exit_port,json=exitPort,proto3" json:"exit_port,omitempty"`
	State     TunnelState            `protobuf:"varint,5,opt,name=state,proto3,enum=knode.v1.TunnelState" json:"state,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastError string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
}

func (x *TunnelInfo) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}
func (x *TunnelInfo) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}
func (x *TunnelInfo) GetExitAddr() string {
	if x != nil {
		return x.ExitAddr
	}
	return ""
}
func (x *TunnelInfo) GetExitPort() int32 {
	if x != nil {
		return x.ExitPort
	}
	return 0
}
func (x *TunnelInfo) GetState() TunnelState {
	if x != nil {
		return x.State
	}
	return TunnelState_TUNNEL_STATE_UNSPECIFIED
}
func (x *TunnelInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}
func (x *TunnelInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}
func (x *TunnelInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *TunnelInfo) Reset()                             { *x = TunnelInfo{} }
func (x *TunnelInfo) String() string                     { return x.TunnelId }

// ============================================================
// Metrics Streaming
// ============================================================

type StreamMetricsRequest struct {
	IntervalSeconds int32 `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
}

func (x *StreamMetricsRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}
func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *StreamMetricsRequest) Reset()                             { *x = StreamMetricsRequest{} }
func (x *StreamMetricsRequest) String() string                     { return "" }

type MetricsEvent struct {
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent     float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent     float64                `protobuf:"fixed64,3,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	DiskPercent    float64                `protobuf:"fixed64,4,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	RxBps          int64                  `protobuf:"varint,5,opt,name=rx_bps,json=rxBps,proto3" json:"rx_bps,omitempty"`
	TxBps          int64                  `protobuf:"varint,6,opt,name=tx_bps,json=txBps,proto3" json:"tx_bps,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,7,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PerCore        []*CoreStatusResponse  `protobuf:"bytes,9,rep,name=per_core,json=perCore,proto3" json:"per_core,omitempty"`
	GoRuntime      *GoRuntimeMetrics      `protobuf:"bytes,10,opt,name=go_runtime,json=goRuntime,proto3" json:"go_runtime,omitempty"`
}

func (x *MetricsEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}
func (x *MetricsEvent) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}
func (x *MetricsEvent) GetRamPercent() float64 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}
func (x *MetricsEvent) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}
func (x *MetricsEvent) GetRxBps() int64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}
func (x *MetricsEvent) GetTxBps() int64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}
func (x *MetricsEvent) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}
func (x *MetricsEvent) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}
func (x *MetricsEvent) GetPerCore() []*CoreStatusResponse {
	if x != nil {
		return x.PerCore
	}
	return nil
}
func (x *MetricsEvent) GetGoRuntime() *GoRuntimeMetrics {
	if x != nil {
		return x.GoRuntime
	}
	return nil
}
func (x *MetricsEvent) ProtoReflect() protoreflect.Message { return nil }
func (x *MetricsEvent) Reset()                             { *x = MetricsEvent{} }
func (x *MetricsEvent) String() string                     { return "" }
