// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: knode/v1/knode.proto

package knodepb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// KnodeServiceClient is the client API for KnodeService service.
type KnodeServiceClient interface {
	// Authentication
	AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Sessions
	ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Cores
	EnableCore(ctx context.Context, in *EnableCoreRequest, opts ...grpc.CallOption) (*EnableCoreResponse, error)
	DisableCore(ctx context.Context, in *DisableCoreRequest, opts ...grpc.CallOption) (*DisableCoreResponse, error)
	CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error)
	AllCoreStatuses(ctx context.Context, in *AllCoreStatusesRequest, opts ...grpc.CallOption) (*AllCoreStatusesResponse, error)
	// Users
	SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error)
	SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error)
	// Traffic
	GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*TrafficReport, error)
	GetUserTraffic(ctx context.Context, in *GetUserTrafficRequest, opts ...grpc.CallOption) (*UserTrafficResponse, error)
	ResetTraffic(ctx context.Context, in *ResetTrafficRequest, opts ...grpc.CallOption) (*ResetTrafficResponse, error)
	// System
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	// Firewall
	OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error)
	ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error)
	ListFirewallRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	// Certificates
	SetCertificates(ctx context.Context, in *SetCertsRequest, opts ...grpc.CallOption) (*SetCertsResponse, error)
	GetCertInfo(ctx context.Context, in *GetCertInfoRequest, opts ...grpc.CallOption) (*CertInfoResponse, error)
	// Outbound Tunnels
	SetupTunnel(ctx context.Context, in *SetupTunnelRequest, opts ...grpc.CallOption) (*SetupTunnelResponse, error)
	TeardownTunnel(ctx context.Context, in *TeardownTunnelRequest, opts ...grpc.CallOption) (*TeardownTunnelResponse, error)
	TunnelStatus(ctx context.Context, in *TunnelStatusRequest, opts ...grpc.CallOption) (*TunnelStatusResponse, error)
	// Metrics Stream (server-side streaming)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEvent], error)
}

type knodeServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewKnodeServiceClient creates a new KnodeServiceClient.
func NewKnodeServiceClient(cc grpc.ClientConnInterface) KnodeServiceClient {
	return &knodeServiceClient{cc}
}

const knodeServiceName = "knode.v1.KnodeService"

func (c *knodeServiceClient) AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/AuthenticateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/ConnectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/DisconnectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/ListSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) EnableCore(ctx context.Context, in *EnableCoreRequest, opts ...grpc.CallOption) (*EnableCoreResponse, error) {
	out := new(EnableCoreResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/EnableCore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) DisableCore(ctx context.Context, in *DisableCoreRequest, opts ...grpc.CallOption) (*DisableCoreResponse, error) {
	out := new(DisableCoreResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/DisableCore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error) {
	out := new(CoreStatusResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/CoreStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) AllCoreStatuses(ctx context.Context, in *AllCoreStatusesRequest, opts ...grpc.CallOption) (*AllCoreStatusesResponse, error) {
	out := new(AllCoreStatusesResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/AllCoreStatuses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error) {
	out := new(SyncUsersResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/SyncUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error) {
	out := new(SetUserLimitsResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/SetUserLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*TrafficReport, error) {
	out := new(TrafficReport)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/GetTraffic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetUserTraffic(ctx context.Context, in *GetUserTrafficRequest, opts ...grpc.CallOption) (*UserTrafficResponse, error) {
	out := new(UserTrafficResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/GetUserTraffic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ResetTraffic(ctx context.Context, in *ResetTrafficRequest, opts ...grpc.CallOption) (*ResetTrafficResponse, error) {
	out := new(ResetTrafficResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/ResetTraffic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/Restart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error) {
	out := new(OpenPortResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/OpenPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error) {
	out := new(ClosePortResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/ClosePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ListFirewallRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/ListFirewallRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetCertificates(ctx context.Context, in *SetCertsRequest, opts ...grpc.CallOption) (*SetCertsResponse, error) {
	out := new(SetCertsResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/SetCertificates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetCertInfo(ctx context.Context, in *GetCertInfoRequest, opts ...grpc.CallOption) (*CertInfoResponse, error) {
	out := new(CertInfoResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/GetCertInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetupTunnel(ctx context.Context, in *SetupTunnelRequest, opts ...grpc.CallOption) (*SetupTunnelResponse, error) {
	out := new(SetupTunnelResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/SetupTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) TeardownTunnel(ctx context.Context, in *TeardownTunnelRequest, opts ...grpc.CallOption) (*TeardownTunnelResponse, error) {
	out := new(TeardownTunnelResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/TeardownTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) TunnelStatus(ctx context.Context, in *TunnelStatusRequest, opts ...grpc.CallOption) (*TunnelStatusResponse, error) {
	out := new(TunnelStatusResponse)
	err := c.cc.Invoke(ctx, "/"+knodeServiceName+"/TunnelStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "StreamMetrics",
		ServerStreams: true,
	}, "/"+knodeServiceName+"/StreamMetrics", cOpts...)
	if err != nil {
		return nil, err
	}
	if err := stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := stream.CloseSend(); err != nil {
		return nil, err
	}
	return &streamMetricsClient{stream}, nil
}

// streamMetricsClient wraps the client stream for StreamMetrics.
type streamMetricsClient struct {
	grpc.ClientStream
}

func (x *streamMetricsClient) Recv() (*MetricsEvent, error) {
	m := new(MetricsEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *streamMetricsClient) Msg() *MetricsEvent {
	m := new(MetricsEvent)
	return m
}

// KnodeServiceServer is the server API for KnodeService service.
// All implementations must embed UnimplementedKnodeServiceServer
// for forward compatibility.
type KnodeServiceServer interface {
	AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error)
	ConnectUser(context.Context, *ConnectRequest) (*ConnectResponse, error)
	DisconnectUser(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	EnableCore(context.Context, *EnableCoreRequest) (*EnableCoreResponse, error)
	DisableCore(context.Context, *DisableCoreRequest) (*DisableCoreResponse, error)
	CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error)
	AllCoreStatuses(context.Context, *AllCoreStatusesRequest) (*AllCoreStatusesResponse, error)
	SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error)
	SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error)
	GetTraffic(context.Context, *GetTrafficRequest) (*TrafficReport, error)
	GetUserTraffic(context.Context, *GetUserTrafficRequest) (*UserTrafficResponse, error)
	ResetTraffic(context.Context, *ResetTrafficRequest) (*ResetTrafficResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Restart(context.Context, *RestartRequest) (*RestartResponse, error)
	OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error)
	ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error)
	ListFirewallRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	SetCertificates(context.Context, *SetCertsRequest) (*SetCertsResponse, error)
	GetCertInfo(context.Context, *GetCertInfoRequest) (*CertInfoResponse, error)
	SetupTunnel(context.Context, *SetupTunnelRequest) (*SetupTunnelResponse, error)
	TeardownTunnel(context.Context, *TeardownTunnelRequest) (*TeardownTunnelResponse, error)
	TunnelStatus(context.Context, *TunnelStatusRequest) (*TunnelStatusResponse, error)
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsEvent]) error
	mustEmbedUnimplementedKnodeServiceServer()
}

// UnimplementedKnodeServiceServer must be embedded for forward compatibility.
type UnimplementedKnodeServiceServer struct{}

func (UnimplementedKnodeServiceServer) AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedKnodeServiceServer) ConnectUser(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUser not implemented")
}
func (UnimplementedKnodeServiceServer) DisconnectUser(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectUser not implemented")
}
func (UnimplementedKnodeServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedKnodeServiceServer) EnableCore(context.Context, *EnableCoreRequest) (*EnableCoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableCore not implemented")
}
func (UnimplementedKnodeServiceServer) DisableCore(context.Context, *DisableCoreRequest) (*DisableCoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableCore not implemented")
}
func (UnimplementedKnodeServiceServer) CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoreStatus not implemented")
}
func (UnimplementedKnodeServiceServer) AllCoreStatuses(context.Context, *AllCoreStatusesRequest) (*AllCoreStatusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllCoreStatuses not implemented")
}
func (UnimplementedKnodeServiceServer) SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUsers not implemented")
}
func (UnimplementedKnodeServiceServer) SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserLimits not implemented")
}
func (UnimplementedKnodeServiceServer) GetTraffic(context.Context, *GetTrafficRequest) (*TrafficReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) GetUserTraffic(context.Context, *GetUserTrafficRequest) (*UserTrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) ResetTraffic(context.Context, *ResetTrafficRequest) (*ResetTrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKnodeServiceServer) Restart(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedKnodeServiceServer) OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenPort not implemented")
}
func (UnimplementedKnodeServiceServer) ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePort not implemented")
}
func (UnimplementedKnodeServiceServer) ListFirewallRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFirewallRules not implemented")
}
func (UnimplementedKnodeServiceServer) SetCertificates(context.Context, *SetCertsRequest) (*SetCertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCertificates not implemented")
}
func (UnimplementedKnodeServiceServer) GetCertInfo(context.Context, *GetCertInfoRequest) (*CertInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertInfo not implemented")
}
func (UnimplementedKnodeServiceServer) SetupTunnel(context.Context, *SetupTunnelRequest) (*SetupTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupTunnel not implemented")
}
func (UnimplementedKnodeServiceServer) TeardownTunnel(context.Context, *TeardownTunnelRequest) (*TeardownTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TeardownTunnel not implemented")
}
func (UnimplementedKnodeServiceServer) TunnelStatus(context.Context, *TunnelStatusRequest) (*TunnelStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TunnelStatus not implemented")
}
func (UnimplementedKnodeServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedKnodeServiceServer) mustEmbedUnimplementedKnodeServiceServer() {}

// UnsafeKnodeServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeKnodeServiceServer interface {
	mustEmbedUnimplementedKnodeServiceServer()
}
